CREATE TABLE "users" (
  "id_user" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "created_at" timestamp DEFAULT (now()),
  "first_name" varchar(20) NOT NULL,
  "last_name" varchar(40) NOT NULL,
  "username" varchar(30) NOT NULL,
  "email" varchar(50) UNIQUE NOT NULL,
  "status" varchar(3) DEFAULT 'ACT',
  "password" varchar(60)
);

CREATE TABLE "tasks_users" (
  "id_user" integer,
  "id_icons" integer,
  "title" integer NOT NULL,
  "detail" text NOT NULL,
  "is_finished" boolean DEFAULT false,
  "added_at" timestamp DEFAULT (now()),
  "ends_at" timestamp DEFAULT (now()),
  "status" varchar(3) DEFAULT 'ACT'
);

CREATE TABLE "icons" (
  "id_icons" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "ico" varchar(1),
  "created_at" timestamp DEFAULT (now()),
  "status" varchar(3) DEFAULT 'ACT'
);

COMMENT ON COLUMN "users"."password" IS 'Content of the post';

ALTER TABLE "tasks_users" ADD FOREIGN KEY ("id_user") REFERENCES "users" ("id_user");

ALTER TABLE "tasks_users" ADD FOREIGN KEY ("id_icons") REFERENCES "icons" ("id_icons");
